### ISSUE TITLE
Sriya's Ticket Week 1 - Project Menu Frontend

### ISSUE THREAD

**Issue by sriyachilla** [nighthawkcoders/nighthawk_society#14]
Week 1 - **Project Menu Frontend** with the following deliverables:
- [x] Link project menu HTML to home page
A. Link to code: [index.html](https://github.com/nighthawkcoders/nighthawk_society/blob/master/templates/homesite/index.html#L39) and [main.py](https://github.com/nighthawkcoders/nighthawk_society/blob/master/main.py#L42-#L44)
B. Link to commit: [Commit #1](https://github.com/nighthawkcoders/nighthawk_society/commit/e8eac0356589d3c4b01c29a5013817ea0a945eae)
C. Link to runtime: [Runtime](http://nighthawkcoders.cf/)
- [x] Utilize Bootstrap template for project menu
A. Link to code: [index.html](https://github.com/nighthawkcoders/nighthawk_society/blob/master/templates/projectsearch.html#L6-#L228)
B. Link to commit: [Commit #1](https://github.com/nighthawkcoders/nighthawk_society/commit/e8eac0356589d3c4b01c29a5013817ea0a945eae)
C. Link to runtime: [Runtime](http://nighthawkcoders.cf/)
- [x] Fix Bootstrap template to make 4 columns
A. Link to code: [index.html](https://github.com/nighthawkcoders/nighthawk_society/blob/master/templates/projectsearch.html#L71-#L85)
B. Link to commit: [Commit #1](https://github.com/nighthawkcoders/nighthawk_society/commit/e8eac0356589d3c4b01c29a5013817ea0a945eae#diff-aa893279ffdb7935c1f098e462ed522c998c0cf9e8883df1ed762cfb586161feR71-R85)
C. Link to runtime: [Runtime](http://nighthawkcoders.cf/)

Ticket for [next week](https://github.com/nighthawkcoders/nighthawk_society/issues/16)

**Comment by sriyachilla** [comment]
Comments:
[From Roop](https://github.com/nighthawkcoders/nighthawk_society/issues/7#issuecomment-847278029)
[From Devam](https://github.com/nighthawkcoders/nighthawk_society/issues/7#issuecomment-847280544)
[From Linda](https://github.com/nighthawkcoders/nighthawk_society/issues/7#issuecomment-847283640)

**Comment by iniyaam** [comment]
Hi Sriya, I looked at the bootstrap link in your ticket and I really liked the card you chose. I think it is a good idea to use bootstrap so the website is compatible with phones. I am looking forward to seeing how the cards look when stacked up and when the page window is expanded/shrunk.

**Comment by ridhimainukurti** [comment]
Hi Sriya, 
I think you gave a very nice description for each of the tickets that you are completing for this week. You also have good links to tangible artifacts. One question I have is that is this issue all one ticket broken down into smaller parts or are you displaying all three of your tickets for the project?

**Comment by ryazhisai** [comment]
Sriya,
Your ticket looks very descriptive and you have tangibles for your accomplishments. I like your organizational structure and feel that it is a good example of what the ticket should look like. One question I have is if you are going to make the cards using the CSS property flex in order to accommodate for the differing sizes in windows.

**Comment by gracele246** [comment]
Hey sriya,
Your ticket has very good description and your tangibles are there. Links to tangibles are working and im excited to see your code. A question I have is are your organizing your tickets down so there isn't as much of a load for code
