### ISSUE TITLE
Umbrella Ticket

### ISSUE THREAD

**Issue by sriyachilla** [nighthawkcoders/nighthawk_society#17]
- [Sriya's Ticket](https://github.com/nighthawkcoders/nighthawk_society/issues/14): Project Menu Frontend
    - Details about ticket in [README](https://github.com/nighthawkcoders/nighthawk_society#readme)
    - Deliverables in [Ticket Issue](https://github.com/nighthawkcoders/nighthawk_society/issues/14)
    - Ticket for [next week](https://github.com/nighthawkcoders/nighthawk_society/projects/1#card-62272026) in "In Progress" column of Scrum Board
- [Iniyaa's Ticket](https://github.com/nighthawkcoders/nighthawk_society/issues/18#issue-909082364): Backend for Comment Code
- [Ridhima's Ticket](https://github.com/nighthawkcoders/nighthawk_society/projects/1#card-62301064) This is the backend for the filtering of the different projects. 
- [Isai's Ticket](https://github.com/nighthawkcoders/nighthawk_society/projects/1#card-62301760) This is the backend for the chat/comment function, specifically the database part.
- [Grace's Ticket](https://github.com/nighthawkcoders/nighthawk_society/issues/21#issue-909818513) Backend of search bar and filtering keywords

**Comment by iniyaam** [comment]
- [Iniyaa's Ticket](https://github.com/nighthawkcoders/nighthawk_society/issues/18#issue-909082364): Backend for Comment Code
