### ISSUE TITLE
Sriya's Tickets

### ISSUE THREAD

**Issue by sriyachilla** [nighthawkcoders/nighthawk_society#7]
- [x] Take notes from prep book & daily videos (Big Ideas 1) – [link to tangible](https://docs.google.com/spreadsheets/d/1cvaRRVcHVbiVJPtf4X0w7vWxC0jOocASFTDNLrVC9KU/edit?usp=sharing)
- [x] Take notes from prep book & daily videos (Big Ideas 2) – [link to tangible]
- [x] Get [Create Task answers](https://docs.google.com/document/d/1S4v7BYQeiM-DfFgz5sm8xtu31t7hvnSxnFHEh_kepuU/edit?usp=sharing) & [program code](https://docs.google.com/document/d/1Doip1bnpuqR9OqiKG2Qh8D4Rh54ygTTnV-7myg4yfiY/edit?usp=sharing) ready to submit
- [ ] Take notes from prep book & daily videos (Big Ideas 3-5)

*Reviewed by Ridhima Inukurti*

**Comment by sriyachilla** [comment]
Sriya's Self-Eval: 3/3
+1 for being an issue in Scrum Board
+1 for checkboxes detailing assignments for all weeks
+1 for links to tangibles (links)

**Comment by jm1021** [comment]
Sriya, not exactly what I was thinking of when planning.  Each of the above should be there own Issue and have breakdowns.  Link to tangible above is interesting, looks like a set of link for your memories not nots on Big Ideas.   The ArtPiece Class code is amazing.    This is something that I hope you were able to explain well to CB.  It exceeds any expectations of their assignment.   This ticket is a little brief.  You should try to communicate more in written word.  4/3, off target on ticket idea -1.

**Comment by LordRoop** [comment]
CSS Mock up looks good. She explained the technical very well. The description of the cards themselves could be a bit more specific. Overall 9/10

**Comment by devamshri** [comment]
Overall, I think you have decent goals, but need to focus on one task since this is specifically meant towards being for the PBL task and not AP exam prep. You can take the "HTML cards" task and specify what you can do with that and what steps it will take to complete that test and you will have a decent card.

**Comment by lindalonglong** [comment]
I think you have measurable and focused goals, it is nice that you assign what videos to watch for each day. You could explain a little more for your 4th goal. Overall 9/10.
